# Generated by Django 5.2.1 on 2025-05-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SyncBotApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, help_text='Enter your full address', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
